// <auto-generated />
using System;
using Academy.Agent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.Agent.Infrastructure.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    [Migration("20260812003358_AddAdminUsersAndNotificationRead")]
    partial class AddAdminUsersAndNotificationRead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy.Agent.Domain.Entities.AcademyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "باقات الحصص",
                            Features = "[\"\\u062D\\u0635\\u062A\\u0627\\u0646 \\u0623\\u0633\\u0628\\u0648\\u0639\\u064A\\u0627\\u064B\",\"\\u0645\\u062A\\u0627\\u0628\\u0639\\u0629 \\u0648\\u062A\\u0642\\u064A\\u064A\\u0645 \\u0645\\u0633\\u062A\\u0645\\u0631\"]",
                            IsActive = true,
                            Name = "باقة حصتين",
                            Notes = "مصر",
                            Period = "شهرياً",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Category = "باقات الحصص",
                            Features = "[\"3 \\u062D\\u0635\\u0635 \\u0623\\u0633\\u0628\\u0648\\u0639\\u064A\\u0627\\u064B\",\"\\u0645\\u062A\\u0627\\u0628\\u0639\\u0629 \\u0648\\u062A\\u0642\\u064A\\u064A\\u0645 \\u0645\\u0633\\u062A\\u0645\\u0631\"]",
                            IsActive = true,
                            Name = "باقة 3 حصص",
                            Notes = "مصر",
                            Period = "شهرياً",
                            Price = 600m
                        },
                        new
                        {
                            Id = 3,
                            Category = "باقات الحصص",
                            Features = "[\"4 \\u062D\\u0635\\u0635 \\u0623\\u0633\\u0628\\u0648\\u0639\\u064A\\u0627\\u064B\",\"\\u0645\\u062A\\u0627\\u0628\\u0639\\u0629 \\u0648\\u062A\\u0642\\u064A\\u064A\\u0645 \\u0645\\u0633\\u062A\\u0645\\u0631\"]",
                            IsActive = true,
                            Name = "باقة 4 حصص",
                            Notes = "مصر",
                            Period = "شهرياً",
                            Price = 800m
                        },
                        new
                        {
                            Id = 4,
                            Category = "باقة العائلة",
                            Features = "[\"3 \\u0623\\u0641\\u0631\\u0627\\u062F \\u0641\\u064A \\u0627\\u0644\\u0628\\u0627\\u0642\\u0629\"]",
                            IsActive = true,
                            Name = "3 أفراد",
                            Notes = "بلانر العائلة",
                            Period = "شهرياً",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 5,
                            Category = "باقة العائلة",
                            Features = "[\"4 \\u0623\\u0641\\u0631\\u0627\\u062F \\u0641\\u064A \\u0627\\u0644\\u0628\\u0627\\u0642\\u0629\"]",
                            IsActive = true,
                            Name = "4 أفراد",
                            Notes = "بلانر العائلة",
                            Period = "شهرياً",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 6,
                            Category = "باقة العائلة",
                            Features = "[\"5 \\u0623\\u0641\\u0631\\u0627\\u062F \\u0641\\u064A \\u0627\\u0644\\u0628\\u0627\\u0642\\u0629\"]",
                            IsActive = true,
                            Name = "5 أفراد",
                            Notes = "بلانر العائلة",
                            Period = "شهرياً",
                            Price = 1700m
                        },
                        new
                        {
                            Id = 7,
                            Category = "مرحلة التصحيح",
                            Features = "[\"\\u062D\\u0635\\u062A\\u0627\\u0646 \\u0641\\u064A \\u0627\\u0644\\u0623\\u0633\\u0628\\u0648\\u0639\"]",
                            IsActive = true,
                            Name = "تصحيح حصتين أسبوعياً",
                            Period = "شهرياً",
                            Price = 500m
                        },
                        new
                        {
                            Id = 8,
                            Category = "مرحلة التصحيح",
                            Features = "[\"3 \\u062D\\u0635\\u0635 \\u0641\\u064A \\u0627\\u0644\\u0623\\u0633\\u0628\\u0648\\u0639\"]",
                            IsActive = true,
                            Name = "تصحيح 3 حصص أسبوعياً",
                            Period = "شهرياً",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "مرحلة ما قبل الإجازة",
                            Features = "[\"\\u062D\\u0635\\u062A\\u0627\\u0646 \\u0641\\u064A \\u0627\\u0644\\u0623\\u0633\\u0628\\u0648\\u0639\",\"\\u0645\\u062F\\u0629 \\u0627\\u0644\\u062D\\u0635\\u0629 \\u0633\\u0627\\u0639\\u0629\"]",
                            IsActive = true,
                            Name = "ما قبل الإجازة",
                            Period = "شهرياً",
                            Price = 800m
                        },
                        new
                        {
                            Id = 10,
                            Category = "مرحلة الإجازة",
                            Features = "[\"\\u062D\\u0641\\u0638 \\u0648\\u0625\\u062C\\u0627\\u0632\\u0629 \\u0627\\u0644\\u0642\\u0631\\u0622\\u0646\"]",
                            IsActive = true,
                            Name = "الإجازة",
                            Period = "شهرياً",
                            Price = 700m
                        },
                        new
                        {
                            Id = 11,
                            Category = "مرحلة الإجازة",
                            Features = "[\"\\u0637\\u0628\\u0627\\u0639\\u0629 \\u0627\\u0644\\u0625\\u062C\\u0627\\u0632\\u0629\",\"\\u0627\\u0644\\u0634\\u062D\\u0646 \\u0634\\u0627\\u0645\\u0644\"]",
                            IsActive = true,
                            Name = "طباعة الإجازة",
                            Period = "مرة واحدة",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 12,
                            Category = "تعليم القراءة للصغار",
                            Features = "[\"\\u0645\\u062F\\u0629 \\u0627\\u0644\\u062D\\u0635\\u0629 40 \\u062F\\u0642\\u064A\\u0642\\u0629\"]",
                            IsActive = true,
                            Name = "حصتان",
                            Period = "شهرياً",
                            Price = 350m
                        },
                        new
                        {
                            Id = 13,
                            Category = "تعليم القراءة للصغار",
                            Features = "[\"\\u0645\\u062F\\u0629 \\u0627\\u0644\\u062D\\u0635\\u0629 40 \\u062F\\u0642\\u064A\\u0642\\u0629\"]",
                            IsActive = true,
                            Name = "3 حصص",
                            Period = "شهرياً",
                            Price = 470m
                        },
                        new
                        {
                            Id = 14,
                            Category = "شرح أحاديث وتربية وتقوية التخاطب وتعديل اللثغة",
                            Features = "[\"\\u064A\\u0648\\u0645\\u0627\\u0646 \\u0623\\u0633\\u0628\\u0648\\u0639\\u064A\\u0627\\u064B\",\"\\u0645\\u062F\\u0629 \\u0627\\u0644\\u062D\\u0635\\u0629 45 \\u062F\\u0642\\u064A\\u0642\\u0629\"]",
                            IsActive = true,
                            Name = "برنامج متكامل",
                            Period = "شهرياً",
                            Price = 880m
                        });
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.AdminNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Delivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationDraftJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Channel", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.PaymentProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("ProofUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TxnRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("PaymentProofs");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PayNow")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredSchedule")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WhatsappPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Academy.Agent.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.PaymentProof", b =>
                {
                    b.HasOne("Academy.Agent.Domain.Entities.Reservation", "Reservation")
                        .WithMany("PaymentProofs")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Academy.Agent.Domain.Entities.AcademyProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Academy.Agent.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("PaymentProofs");
                });
#pragma warning restore 612, 618
        }
    }
}
